name: "Build"
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: armbian/build@main
        with:
          armbian_target:             "build"
          armbian_release:            "sid"
          armbian_kernel_branch:      "edge"
          armbian_ui:                 "kde-plasma"
          armbian_board:              "kde-plasma"
          armbian_release_tittle:     "Armbian OPI3B KDE"
          armbian_release_body:       "Armbian Sid for Orange Pi 3B with KDE Plasma desktop."
